version: '3.3'

services:
  web:
    image: spotiplays
    build:
      context: .
    devices:
      - /dev/snd
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    ports:
      - 8000:8010
    command: uvicorn --port 8010 --host 0.0.0.0 --loop uvloop main:app
    depends_on:
      - migrate

  migrate:
    image: spotiplays
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    command: alembic upgrade head

  homeassistant:
    # Use homeassistant/raspberrypi3-homeassistant:stable image for raspberry Pi
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hass/:/config/
    ports:
    - 8123:8123
    restart: always
