version: '3.3'

services:
  web:
    image: spotiplays
    build:
      context: .
    devices:
      - /dev/snd
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    ports:
      - 8000:8010
    restart: unless-stopped
    command: uvicorn --port 8010 --host 0.0.0.0 --loop uvloop main:app

  migrate:
    image: spotiplays
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    command: alembic upgrade head
