version: '3.8'

services:
  web:
    build:
      context: .
    devices:
      - /dev/snd
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
      - ./spotifyd/spotifyd.conf:/etc/spotifyd.conf:ro
    ports:
      - 8000:8010
    command: uvicorn --port 8010 --host 0.0.0.0 --loop uvloop main:app

#  homeassistant:
#    # Use homeassistant/raspberrypi3-homeassistant:stable image for raspberry Pi
#    image: homeassistant/home-assistant:stable
#    volumes:
#      - ./hass/:/config/
#    network_mode: host
#    restart: always

volumes:
  spotifyd_tmp:
