version: '3.3'

services:
  web:
    image: spotiplays
    build:
      context: .
    devices:
      - /dev/snd
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    ports:
      - 8000:8010
#    networks:
#      - hass
    restart: unless-stopped
    command: uvicorn --port 8010 --host 0.0.0.0 --loop uvloop main:app

# Network for develop HA config
#networks:
#  hass:
#    external:
#      name: hass
