version: '3.3'

services:
  web:
    image: spotiplays
    build:
      context: .
    devices:
      - /dev/snd
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    ports:
      - 8000:8010
    restart: always
    command: uvicorn --port 8010 --host 0.0.0.0 --loop uvloop main:app
    depends_on:
      - migrate

  migrate:
    image: spotiplays
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/opt/project
    command: alembic upgrade head

  homeassistant:
    image: homeassistant/home-assistant:2020.12.1
    volumes:
      - ./hass-config/:/config/
    ports:
    - 8123:8123
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config
    restart: unless-stopped

  valmapper:
    image: rand256/valetudo-mapper
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 3000:3000


volumes:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:

