name: Lint and Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: flake8
      run: |
        cd src && flake8

    - name: mypy
      run: |
        cd src && mypy -m api

    - name: pytest
      run: |
        cd src && mypy tests && pytest
